spring:
  datasource:
    druid:
        driver-class-name: com.mysql.jdbc.Driver
        url: jdbc:mysql://127.0.0.1:3306/viewshare_mvr?useSSL=false&useUnicode=true&amp;characterEncoding=UTF-8&allowMultiQueries=true&autoReconnect=true
        username: root
        password: root
        initial-size: 3
        min-idle: 3
        max-active: 3
        max-wait: 60000
        time-between-eviction-runs-millis: 60000
        min-evictable-idle-time-millis: 300000
        validation-query: SELECT 1 FROM DUAL
        test-while-idle: true
        test-on-borrow: true
        test-on-return: false
        pool-prepared-statements: true
        max-pool-prepared-statement-per-connection-size: 20
        filters: stat,wall,log4j
        connection-properties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000