spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.01:3306/viewshare_mvr?useSSL=false&useUnicode=true&amp;characterEncoding=UTF-8&allowMultiQueries=true
    data-username: root
    data-password: root